angrypigs-$ENVIRONMENT:
  scale: 1
  environment:
    ENVIRONMENT: $ENVIRONMENT
  tty: false
  ports:
    - 5000/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: asg_name=rancher-operations-o1
  image: $DOCKER_IMAGE
  upgrade_strategy:
    start_first: false
    batch_size: 1
